[package]
name = "safe_bindgen"
version = "0.5.0"
authors = ["Sean Marshallsay <srm.1708@gmail.com>",
           "Matthew Gregan <kinetik@flim.org>",
           "MaidSafe Developers <dev@maidsafe.net>"]

description = "A library to automatically generate C and Java files from Rust source files."
readme = "README.md"
keywords = ["c", "header", "ffi"]

homepage = "https://github.com/mozilla/moz-cheddar"
repository = "https://github.com/mozilla/moz-cheddar"
documentation = "https://docs.rs/moz-cheddar"

license = "MIT"

[features]
default = ["with-syntex"]
with-syntex = [
    "syntex_errors",
    "syntex_syntax",
]

[lib]
name = "safe_bindgen"
path = "src/lib.rs"

[[bin]]
name = "bindgen"
doc = false
path = "src/bin/bindgen.rs"

[dependencies]
syntex_errors = {version = "0.58.1", optional = true}
syntex_syntax = {version = "0.58.1", optional = true}
toml = "0.3.2"
clap = "2"
Inflector = "0.10.1"
jni = "0.7.2"
quote = "0.3.15"